apiVersion: karpenter.k8s.aws/v1
kind: EC2NodeClass
metadata:
  name: spot-small
spec:
  amiFamily: AL2023
  role: arn:aws:iam::058264369873:role/my-eks-cluster-karpenter-node
  subnetSelectorTerms:
    - tags:
        Name: my-eks-cluster-private-*
  securityGroupSelectorTerms:
    - tags:
        karpenter-discovery/my-eks-cluster: "*"
  amiSelectorTerms:
    - alias: al2023@v20240703
  metadataOptions:
    httpEndpoint: enabled
    httpTokens: required
  tags:
    Name: karpenter-spot
    Project: my-eks-cluster
    karpenter.sh/discovery: my-eks-cluster