apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: spot-small
spec:
  template:
    metadata:
      labels:
        type: spot
    spec:
      nodeClassRef:
        name: spot-small
        kind: EC2NodeClass
        group: karpenter.k8s.aws
      taints:
        - key: "spotOnly"
          value: "true"
          effect: "NoSchedule"
      requirements:
        - key: "karpenter.sh/capacity-type"
          operator: In
          values: ["spot"]
        - key: "node.kubernetes.io/instance-type"
          operator: In
          values: ["t3.small", "t3.medium"]
  limits:
    cpu: "4"
  disruption:
    consolidationPolicy: WhenEmptyOrUnderutilized
    consolidateAfter: 30s
  weight: 10