# test-pod.yaml
apiVersion: v1
kind: Pod
metadata:
  name: curl-test
  namespace: karpenter
spec:
  serviceAccountName: karpenter
  containers:
    - name: curl
      image: curlimages/curl:latest
      command: ["sleep", "3600"]
