apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: db-secret
  namespace: default
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-parameterstore
    kind: ClusterSecretStore
  target:
    name: db-secret
    creationPolicy: Owner
  data:
    - secretKey: db-host
      remoteRef:
        key: /my-eks-cluster-db/db-host
    - secretKey: db-username
      remoteRef:
        key: /my-eks-cluster-db/db-username
    - secretKey: db-password
      remoteRef:
        key: /my-eks-cluster-db/db-password