apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  annotations:
    karpenter.sh/nodepool-hash: "6821555240594823858"
    karpenter.sh/nodepool-hash-version: v3
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"karpenter.sh/v1","kind":"NodePool","metadata":{"annotations":{"kubernetes.io/description":"Cheap spot nodes (≤2 vCPU, ≤4GB RAM, EBS, 5-10Gbps net)"},"name":"spot"},"spec":{"disruption":{"consolidateAfter":"1h","consolidationPolicy":"WhenEmptyOrUnderutilized"},"limits":{"cpu":"4","memory":"8Gi"},"template":{"spec":{"nodeClassRef":{"group":"karpenter.k8s.aws","kind":"EC2NodeClass","name":"default"},"requirements":[{"key":"karpenter.sh/capacity-type","operator":"In","values":["spot"]},{"key":"node.kubernetes.io/instance-type","operator":"In","values":["t3.medium"]},{"key":"kubernetes.io/arch","operator":"In","values":["amd64"]},{"key":"kubernetes.io/os","operator":"In","values":["linux"]}]}}}}
    kubernetes.io/description: Cheap spot nodes (≤2 vCPU, ≤4GB RAM, EBS, 5-10Gbps
      net)
  creationTimestamp: "2025-07-17T18:09:46Z"
  generation: 7
  name: spot
  resourceVersion: "33353"
  uid: 51d312ea-d682-436d-b579-ba6de1353394
spec:
  disruption:
    budgets:
    - nodes: 10%
    consolidateAfter: 1m
    consolidationPolicy: WhenEmptyOrUnderutilized
  limits:
    cpu: "4"
    memory: 8Gi
  template:
    spec:
      expireAfter: 720h
      nodeClassRef:
        group: karpenter.k8s.aws
        kind: EC2NodeClass
        name: default
      requirements:
      - key: karpenter.sh/capacity-type
        operator: In
        values:
        - spot
      - key: node.kubernetes.io/instance-type
        operator: In
        values:
        - t3.medium
        - t3a.medium
      - key: kubernetes.io/arch
        operator: In
        values:
        - amd64
      - key: kubernetes.io/os
        operator: In
        values:
        - linux
status:
  conditions:
  - lastTransitionTime: "2025-07-17T18:09:46Z"
    message: ""
    observedGeneration: 7
    reason: ValidationSucceeded
    status: "True"
    type: ValidationSucceeded
  - lastTransitionTime: "2025-07-17T18:09:46Z"
    message: ""
    observedGeneration: 7
    reason: NodeClassReady
    status: "True"
    type: NodeClassReady
  - lastTransitionTime: "2025-07-17T18:55:20Z"
    message: object is awaiting reconciliation
    observedGeneration: 7
    reason: AwaitingReconciliation
    status: Unknown
    type: NodeRegistrationHealthy
  - lastTransitionTime: "2025-07-17T18:55:20Z"
    message: ""
    observedGeneration: 7
    reason: Ready
    status: "True"
    type: Ready
  nodeClassObservedGeneration: 1
  resources:
    cpu: "0"
    ephemeral-storage: "0"
    memory: "0"
    nodes: "0"
    pods: "0"
